# port of noctis viola from vscode

##################### ui elements ############################
'ui.background' = { fg = "text", bg = "editor-bg" } # default background color.
'ui.background.separator' = { fg = "jagger" }                     # picker separator below input line
'ui.linenr' = { fg = "disabled-text-fg" }
'ui.linenr.selected' = { fg = "active-text-fg" }

# 'ui.statusline' = { bg = "#654d80" }
'ui.statusline' = { bg = "editor-bg", fg = "active-text-fg"} # Status line on active split
'ui.statusline.inactive' = { bg = "editor-bg", fg = "disabled-text-fg" } # Status line on inactive split
'ui.statusline.insert' = { bg = "turquoise", fg = "#171d1e" } # Mode indicator for INSERT mode
'ui.statusline.select' = { bg = "light-blue", fg = "#171d1e" } # Mode indicator for SELECT mode

'ui.popup' = { bg = "popup-bg" } # Popups
'ui.popup.info' = { bg = "popup-bg" }

'ui.window' = { fg = "editor-border" } # Border lines separating splits

'ui.selection' = { bg = "selected-text-bg" }
'ui.cursor.primary' = { bg = "text", fg = "editor-bg" }
'ui.cursor.select' = { bg = "text" } # The cursor icon in SELECT mode
'ui.cursor.insert' = { bg = "text" } # The cursor icon in INSERT mode
'ui.cursor.match' = { bg = "#49D6E9", fg = "editor-bg", modifiers = ["bold"]} # Bracket matching

'ui.cursorline.primary' = { bg = "cursorline-bg" }

'ui.menu' = { bg = "popup-bg" }
'ui.menu.selected' = { bg = "popup-selected" }
# 'ui.menu.scroll'

# 'diagnostic.hint'
'diagnostic.info' = { fg = "green" }
'diagnostic.warning' = { fg = "macaroni-and-cheese", underline = { style = "curl" } }
'diagnostic.error' = { fg = "cinnabar", underline = { style = "curl" } }

'diff.plus' = { fg = "light-green" }
'diff.minus' = { fg = "cinnabar" }
'diff.delta' = { fg = "macaroni-and-cheese" }

########## syntax highlighting ##########
'type' = { fg = "copper" }
'type.enum.variant' = { fg = 'copper' }

'constructor' = { fg = "copper" }

'constant' = { fg = 'galliano' }
'constant.builtin.boolean' = { fg = "medium-slate-blue" }

'variable' = { fg = "maize" }
'variable.other.member' = { fg = "text" }

'comment' = { fg = "deluge" } # this is a comment.

'comment.line' = {}                # line comments, like this.
'comment.block' = {}               # block comments, like /* this */ in some languages.
'comment.block.documentation' = {} # doc comments, e.g '///' in rust.

'keyword' = { fg = "pale-violet-red" }
'keyword.storage.type' = { fg = "pale-violet-red" }
'keyword.storage.modifier' = { fg = "pale-violet-red" }
'keyword.control.import' = { fg = "orange-keyword-fg" }
'keyword.function' = { fg = 'orange-keyword-fg' }
'keyword.operator' = { fg = "pale-violet-red" }
'keyword.operator.borrow' = { fg = "pale-violet-red" }

'function' = { fg = "function-name-fg" }

# 'punctuation' = { fg = "gold", modifiers = ["bold"] }  # (){}[]:;,.
'punctuation' = { modifiers = ["bold"] }
'punctuation.delimiter' = { fg = "text" }     # commas and colons.
'punctuation.bracket.type_arguments' = { fg = 'text' }


'namespace' = { fg = "light-blue" } # * namespace keyword in java, c#, etc.

'string' = { fg = "string-fg" }

######## diagnostics ########

# diffs


# gutter area errors and warnings
'info' = { fg = "magenta" }
'warning' = { fg = "twine" }
'error' = { fg = "cinnabar" }
'hint' = { fg = "light-blue" }
# editing area errors and warnings
#'diagnostic' = { fg = 'cyan' }


####### rulers and indent guides #######
# 'ui.virtual.ruler' = { bg = "butterfly-bush" }
'ui.virtual' = { fg = "jagger" }
'ui.virtual.ruler' = { fg = "dimmed-border" }
'ui.virtual.indent-guide' = { fg = "dimmed-border" }
'ui.virtual.inlay-hint' = { fg = "east-side", modifiers = ["dim"] }

######## buffer lines #######
# 'ui.bufferline' = { bg = 'background' }
'ui.bufferline' = { bg ='editor-bg' }
'ui.bufferline.active' = { bg = "#654d80" }


########### status line #######
# ui.statusline


[palette]
copper = "#d67e5c"
galliano = "#d5971a"
maize = "#e4b781"
pale-violet-red = "#df769b"
medium-slate-blue = "#7060eb"
deluge = "#7f659a"
east-side = "#b2a2c3"
jagger = "#413253"
ce-soir = "#8767a8"
light-green = "#8ce99a"


text = "#ccbfd9"
cinnabar = "#e34e1c"
macaroni-and-cheese = "#fec080"
twine = "#c48254"
butterfly-bush = "#765992"
tolopea = "#2b2136"

turquoise = "#49e9a6"
line-number-fg = "#5e5973"
# lilac-bush = "#996bc7"
orange-keyword-fg = "#e66533"
function-name-fg = "#16a3b6"
brackets-fg = "#ccbfd9"
light-blue = "#49d6e9"
string-fg = "#49e9a6"
# popup-background = "#3d2e4d"
# popup-selected = "#472e60"


editor-bg = "#30243D"
popup-bg = "#462D5D"

dimmed-border = "#473856"
# ruler-fg = "#473856"
indent-guide-fg = "#473856"
editor-border = "#3D2E4D"
toolbar-bg = "#3D2E4D"
disabled-text-fg = "#665970"
active-text-fg = "#996BC7"
selected-text-bg = "#4C3A60"
cursorline-bg = "#3E2D51"
